<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE Rezepteseite [
	<!ELEMENT Rezeptseite (Rezept+)>
	<!ELEMENT Rezept (Rezeptname, Bild*, Zutaten, Zubereitung)>
	<!ELEMENT Zutaten (Zutat+)>
	<!ELEMENT Zutat (Zutatname,Menge)>

	<!ELEMENT  Rezeptname (#PCDATA)>	
	<!ELEMENT  Bild (#PCDATA)>
	<!ELEMENT  Zutatname (#PCDATA)>
	<!ELEMENT  Menge (#PCDATA)>
	<!ELEMENT  Arbeitszeit (#PCDATA)>
	<!ELEMENT  Schwierigkeitsgrad (#PCDATA)>
	<!ELEMENT  Brennwert (#PCDATA)>
	<!ELEMENT  Beschreibung (#PCDATA)> 
	
	<!ATTLIST Rezeptseite URL CDATA #REQUIRED>
	<!ATTLIST Rezept id CDATA  #REQUIRED>
	<!ATTLIST Rezept kategorie CDATA #IMPLIED>
	<!ATTLIST Bild beschreibung CDATA #IMPLIED>
	<!ATTLIST Zutaten portionen CDATA #REQUIRED>
	<!ATTLIST Menge einheit CDATA #IMPLIED>
	]>


<!-- XML Datei mit Beispieldaten-->

<Rezepteseite URL="http://www.chefkoch.de/">
 	<Rezept id="1234" kategorie="Backen">
 		<Rezeptname>Lenchen’s Schokoladenkuchen</Rezeptname>
		<Bild beschreibung="1/60: Foto von Dennis">schoko.jpg</Bild>
		
		<Zutaten portionen="16">
			 <Zutat>
				<Zutatname>Butter</Zutatname>
			 	<Menge einheit="g">200</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Zucker</Zutatname>
			 	<Menge einheit="g">200</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Schokolade, Blockschokolade</Zutatname>
			 	<Menge einheit="g">200</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Mehl</Zutatname>
			 	<Menge einheit="g">120</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Backpulver</Zutatname>
			 	<Menge einheit="TL">1/2</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Vanillezucker</Zutatname>
			 	<Menge einheit="Pkt">1</Menge>
			 </Zutat>
			 <Zutat>
				<Zutatname>Ei(er)</Zutatname>
			 	<Menge einheit="">4</Menge>
			 </Zutat>
		</Zutaten>
		
		<Zubereitung>
			<Arbeitszeit>ca. 1 Std.</Arbeitszeit>
			<Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
			<Brennwert>295 kcal</Brennwert>
			<Beschreibung>Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. 
				      Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen 
				      und mischen. Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen 
		         	      Eiweiße vorsichtig unterheben. In eine gut gefettete Form geben. 
				      Bei 180°Grad 40 – 50 Minuten backen.</Beschreibung>
		</Zubereitung>
	
	</Rezept>
</Rezepteseite>




<!-- Autor Dennis Meyer -->
