=== Shufro/wba2_ss13/Phase 1/Aufgabe 3/Aufgabe3dV2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- XML Schema divided -->

<!-- Definition einfache Elemente mit Restrictions -->
<xs:element name="Rezeptname">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Kurzinfo">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="20"/>
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Zutatname">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:maxLength value="40"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Menge">
  <xs:simpleType>
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
      <xs:maxInclusive value="1000"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Schwierigkeitsgrad">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="simpel"/>
      <xs:enumeration value="normal"/>
      <xs:enumeration value="pfiffig"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="Beschreibung" type="xs:string"/>
<xs:element name="Arbeitszeit" type="xs:string"/>
<xs:element name="Ruhezeit" type="xs:string"/>
<xs:element name="Koch-Backzeit" type="xs:string"/>
<xs:element name="Brennwert" type="xs:string"/>



<!-- Definition Attribute -->
<xs:attribute name="url" type="xs:string"/>
<xs:attribute name="rezeptid" type="xs:integer"/>
<xs:attribute name="kategorie" type="xs:string"/>
<xs:attribute name="bildbeschreibung" type="xs:string"/>
<xs:attribute name="mengeneinheit" type="xs:string" default="0"/>
<xs:attribute name="bildquelle" type="xs:string"/>


<xs:attribute name="portionen">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="0"/>
      <xs:maxInclusive value="50"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>


<!-- Definition komplexe Elemente -->

<!-- Wurzelelement -->
<xs:element name="Rezepteseite">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Rezept" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<!-- einzelnes Rezept -->
<xs:element name="Rezept">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Rezeptname"/>
      <xs:element ref="Kurzinfo" minOccurs="0"/>
      <xs:element ref="Bilder" minOccurs="0"/>
      <xs:element ref="Zutaten"/>
      <xs:element ref="Zubereitung"/>
	</xs:sequence>   	
<xs:attribute ref="rezeptid" use="required"/>
    <xs:attribute ref="kategorie" use="required"/>
    <xs:attribute ref="url"/>
  </xs:complexType>
</xs:element>


<!-- Bilder -->
<xs:element name="Bilder">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Bild" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="Bild">
  <xs:complexType>
  	<xs:attribute ref="bildbeschreibung" use="required"/>
    <xs:attribute ref="bildquelle" use="required"/>
  </xs:complexType>
</xs:element>


<!-- Zutaten -->
<xs:element name="Zutaten">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Zutat" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute ref="portionen" use="required"/>
  </xs:complexType>
</xs:element>

<!-- einzelne Zutat mit zugehÃ¶rigen Informationen -->
<xs:element name="Zutat">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Zutatname"/>
      <xs:element ref="Menge"/>
    </xs:sequence>
    <xs:attribute ref="mengeneinheit" use="required"/>
  </xs:complexType>
</xs:element>


<!-- Zubereitung -->
<xs:element name="Zubereitung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Arbeitszeit"/>
      <xs:element ref="Schwierigkeitsgrad"/>
      <xs:element ref="Brennwert"/>
      <xs:element ref="Ruhezeit" minOccurs="0"/>
      <xs:element ref="Koch-Backzeit" minOccurs="0"/>
      <xs:element ref="Beschreibung"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>



</xs:schema>

=== Shufro/wba2_ss13/Phase 1/Aufgabe 3/Aufgabe3dV2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Rezepteseite xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="Aufgabe3dV2.xsd">
	
	<!-- Beispieldatensatz 1 -->
	
	<Rezept rezeptid="1010591206190843" kategorie="Kekse" url="http://www.chefkoch.de/rezepte/1010591206190843/Lothars-beste-Nuernberger-Elisenlebkuchen.html">
		<Rezeptname>Lothars beste Nürnberger Elisenlebkuchen</Rezeptname>
		<Kurzinfo>weihnachtliches Nachbarschaftsrezept</Kurzinfo>
		<Bilder>
			<Bild bildbeschreibung="1/29: Foto von Ursula54" bildquelle="leckerkekse.jpg"/>
		</Bilder>
	
		<Zutaten portionen="1">
				<Zutat mengeneinheit="Anzahl">
					<Zutatname>Ei(er)</Zutatname>
					<Menge>6</Menge>
				</Zutat>
				<Zutat mengeneinheit="g">
					<Zutatname>Zucker, braun</Zutatname>
					<Menge>180</Menge>
				</Zutat>
				<Zutat mengeneinheit="EL">
					<Zutatname>Honig</Zutatname>
					<Menge>2</Menge>
				</Zutat>
				<Zutat mengeneinheit="g">
					<Zutatname>Haselnüsse, gemahlen</Zutatname>
					<Menge>250</Menge>
				</Zutat>
		</Zutaten>
	
		<Zubereitung>
			<Arbeitszeit>25 Minuten</Arbeitszeit>
			<Schwierigkeitsgrad>simpel</Schwierigkeitsgrad>
			<Brennwert>keine Angabe</Brennwert>   			
			<Beschreibung>Eier, Zucker und Honig schön schaumig schlagen. Die restlichen Teigzutaten untermischen. Den Teig flach auf die Oblaten streichen (ergibt ca. 30 St./90 mm oder ca. 40 St./70 mm). 
				      Auf das mit Backpapier ausgelegte Blech legen. Backen mit Ober- und Unterhitze bei 150°, ca. 20 Minuten.
                                      Nach dem Erkalten evtl. mit Kuvertüre überziehen.
        	</Beschreibung>
		</Zubereitung>
	</Rezept>
	
	
	
	<!-- Beispieldatensatz 2 -->
	
	<Rezept rezeptid="485281142608656" kategorie="Wild" url="http://www.chefkoch.de/rezepte/485281142608656/Rehruecken-ausgeloest.html">
		<Rezeptname>Rehrücken ausgelöst</Rezeptname>
		<Zutaten portionen="6">
				<Zutat mengeneinheit="Anzahl">
					<Zutatname>Rehrücken</Zutatname>
					<Menge>1</Menge>
				</Zutat>
				<Zutat mengeneinheit="Anzahl">
					<Zutatname>Wacholderbeeren</Zutatname>
					<Menge>10</Menge>
				</Zutat>
				<Zutat mengeneinheit="g">
					<Zutatname>Butter</Zutatname>
					<Menge>100</Menge>
				</Zutat>			
				<Zutat mengeneinheit="EL">
					<Zutatname>Olivenöl</Zutatname>
					<Menge>4</Menge>
				</Zutat>
				<Zutat mengeneinheit="Anzahl">
					<Zutatname>Zwiebel mit Schale</Zutatname>
					<Menge>1</Menge>
				</Zutat>
				<Zutat mengeneinheit="TL">
					<Zutatname>Pfeffer</Zutatname>
					<Menge>1</Menge>
				</Zutat>
				<Zutat mengeneinheit="TL">
					<Zutatname>Senf</Zutatname>
					<Menge>1</Menge>
				</Zutat>
				<Zutat mengeneinheit="TL">
					<Zutatname>Salz</Zutatname>
					<Menge>1</Menge>
				</Zutat>
				<Zutat mengeneinheit="TL">
					<Zutatname>Balsamico</Zutatname>
					<Menge>1</Menge>
				</Zutat>
		</Zutaten>
	
		<Zubereitung>
			<Arbeitszeit>2 Stunden</Arbeitszeit>
			<Schwierigkeitsgrad>pfiffig</Schwierigkeitsgrad>
			<Brennwert>keine Angabe</Brennwert>			
            <Ruhezeit>1 Tag</Ruhezeit>
   			<Beschreibung>Ein Rehrücken ist eine edle Sache. Er macht am Tag der Zubereitung wenig Arbeit, verlangt beim Braten aber Fingerspitzengefühl und 10-12 Minuten die ungeteilte Aufmerksamkeit des Koches. 
   				      Ich möchte den Rücken rosa gebraten und wenn er dann nur 2 Minuten zu lange im Offen war, ist er durchgebraten, und seine einmalige Zartheit geht verloren.
        		 	      Zunächst die Überlegung, Rehrücken im Ganzen zu braten oder auszulösen? Ich löse immer aus, weil ich so den Garprozess besser beurteilen und aus den Knochen eine leckere Sauce machen kann. 
        			      Das wird ein oder zwei Tage vor dem Verzehr gemacht. [...]
        	</Beschreibung>
		</Zubereitung>
	</Rezept>
	
</Rezepteseite>
